apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  replicas: 2
  selector:
    matchLabels:
     app: tomcat
  template:
    metadata:
     labels:
       app: tomcat
    spec:
     imagePullSecrets:
       - name: dockerpasswd1
     containers:
       - name: tomcat
         image:  cdtsbikaner/tomcat:v1
         ports:
          - containerPort: 8080
      
