apiVersion: v1
kind: Service
metadata:
  name: tgsvc
spec:
  type: NodePort
  selector:
    matchLabels:
     app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
