name: Build and Push Docker Image from EC2

on:
  workflow_dispatch:  # or push

jobs:
  build-and-push:
    runs-on: self-hosted  # this means it'll run on your EC2 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t cdtsbikaner/ecbmcafeb25:latest .

      - name: Tag image
        run: docker tag cdtsbikaner/ecbmcafeb25:latest cdtsbikaner/ecbmcafeb25:latest
      - name: Push image to Docker Hub
        run: docker push cdtsbikaner/ecbmcafeb25:latest
